version: "2"

linters:
  default: none
  enable:
    - wastedassign
    - unused
    - errcheck
    - ineffassign
    - govet
    - staticcheck

  exclusions:
    rules:
      - path: examples
        linters:
          - errcheck # do not run errcheck for examples folder to keep examples as simple as possible
      - path: benchmark/ecs_benchmark_test.go
        linters:
          - errcheck # do not run errcheck for ecs benchmarks

    # do not run any lints for the following paths:
    paths-except:
      - sandbox
